version: '3.9'

services:

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: super_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    restart: on-failure
    volumes:
      - ./infra/mysql/config.sql:/docker-entrypoint-initdb.d/data.sql

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  localstack:
    image: localstack/localstack-pro
    container_name: localstack
    env_file: ./infra/s3connector/s3connector-deploy.env
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "53:53"                # DNS config (required for Pro)
      - "53:53/udp"            # DNS config (required for Pro)
      - "443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./infra/s3connector/localstack/volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
